# -*- coding: utf-8 -*-
"""Guessing game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a87-mQ8YBdLdJrYzfkt3cjK51zQuQ93q
"""

import random

def computerGuess(lowval,highval,randnum,count=0):
  if highval>lowval:
    guess=lowval+(highval-lowval)//2
    
    # if guess is in the middle it is found
    if guess==randnum:
      return count
    
      # if guess is greater than the number 
      # it is found in the lower half of the set of numbers
      # between the lower value and the guess
    elif guess>randnum:
      count=count+1
      return computerGuess(lowval,guess-1,randnum,count)
      
      # the number must be in the upper set of the number
      # between the guess and the upper value
    else:
      count=count+1
      return computerGuess(guess+1,highval,randnum,count)
  else:
    # number not found
    return -1
#end of function

#generate a random number between 1 to 100
randnum=random.randint(1,101)
count=0
guess=-99
while(guess!=randnum):
  # get the users guess
  guess=int(input("Enter guess between 1 and 100:"))
  if guess<randnum:
    print("Higher")
  elif guess>randnum:
    print("Lower")
  else:
    print("You guessed it!")
    break
  count=count+1
# end of while loop
print("You took",str(count),"no. of chances to guess the number")
print("Computer took",str(computerGuess(0,100,randnum)),"chances to guess the number")

